import random, os, sys, time, importlib
from plugin.focus import focus
from plugin.gen_shortcut import gen_shortcut

# Import statements above are automatically generated by reload_commands.py

help_dot_path = "core.kpython_help"
reload_dot_path = "core.reload_commands"


def command_handler(command):
    """
    This is the engine to process a command.
    """
    if command == "help":
        help_module = importlib.import_module(help_dot_path)  # Dynamically import help module.
        getattr(help_module, help_dot_path[5:])()  # Get the help function.
    elif command == "reload":
        reload_module = importlib.import_module(reload_dot_path)
        getattr(reload_module, reload_dot_path[5:])()
    else:
        try:
            ans = eval(command)
            if ans is not None:
                print("The command returned:", ans)
        except Exception as e:
            print("An error occurred:", e)


if __name__ == "__main__":
    help_dot_path = "kpython_help"
    reload_dot_path = "reload_commands"
    command_handler("help")
